sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js
cache:
  yarn: true
  directories:
    - "node_modules"
node_js: '8'

stages:
  - name: lint + test + security-tests
  - name: test-with-coverage
    if: (branch = master AND NOT (type = pull_request))
  - name: smoke-test
  - name: deploy
    if: (branch = master AND NOT (type = pull_request))

install:
  - yarn install

before_script:
  - yarn run build-css

jobs:
  include:
    - stage: lint + test + security-tests
      script: yarn lint
    - script: yarn test
    - 
      install: skip
      before_script: skip
      services:
        - docker
      script: bash ci/security-checks.sh
    - stage: test-with-coverage
      script: yarn test-coverage
    - stage: smoke-test
      install:
      before_script:
        - chmod +x ./tests/functional/runSmokeTest.sh
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - sleep 3
        - yarn start --detach 2>&1 &
        - sleep 5
      script: ./src/tests/functional/runSmokeTest.sh
      after_script:
        - pkill node
    - stage: deploy
      before_script:
        - yarn run build-css
        - yarn build
      deploy:
        provider: firebase
        skip_cleanup: true
        local_dir: build
        on:
          branch: master

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a387d084c573fd34e585
    on_success: change
    on_failure: always
    on_start: always

